language: node_js
node_js:
- '12'
- '14'
services:
- redis-server
script:
- echo 'Starting'
- npm install
- echo 'Testing'
- npm test
deploy:
  provider: heroku
  api_key:
    secure: ho2xjdwQWuK+U++9o67cxVQ1WnXv0lrdCZbrr5sRkYd5NLhLEf4QY5rY0VV6HyI8oee6J/2MacGUIUXBI2M36wdDBjtFKA1P0z3OTUyhB6MOWbKdinIQTNUCmsDcinNdGnmBD/Flc7bH2NuuUiXGjp9d1MJHbh90msBDWe8sve46mNhalQVCeX0ONnUFagYW1Y4RCYz3XPZbYF6uUt6B59c3JOqGTZoGvd7+ORy8JBs9ci0J/XXD0UIDcLP08kM4SQB/B+rBKHQRSJtiiN/QuGYjgRo+uF2wkvfIt8QWqWgZqRC8jQTm1Bbe+SF9rIG1YGiCPaEWPWRPE3k68CivhjbNCgs0Wy5ktt2MV1j7Qo1gOwlEoHlyNbMbxjsuliCp7vjgT0/rb2r38iffFxGBCO4+OgK7T6we14l8DIedU3UgLXH/0bE0iU/eCAGUb6sfSn+aFz1m+i9QPBZNY9QP+4It8cT901B1t62QeGPN/GP39SIWsZfaCkXEHosoRlpU62E8wA5CDy41L3E3RZJDF9x28cH4Y4L/ky89MWZ2QRfqI+owN7XWbyCOIMZFTEoi0lQOso+gbGDLaLEYmX13urwy43STKJRQSD/UTrsUaNJ3OUQ55wByKXUcyRMkbXcXTGyKhsjJh/AmzR7R0lvoSL4LUQTIiSRR3qiCrDD0Ezs=
  app: devops-lab5
  on:
    repo: RaphaelBhnk/LaBDevops
    branch: main
  skip_cleanup: 'true' 
